
如何捕获一个线程抛出的异常？

throw与throws的区别
```text
throw用于方法内部，throws用于方法声明上

throw后面跟异常对象，throws后跟异常类型

throw后只能跟一个异常对象，throws后可以跟多种异常类型

```

在异常处理中，若try中的代码可能产生多种异常则可以对应多个catch语句，若catch中的参数类型有父类子类关系，此时应该将父类放在后面，子类放在前面。
（正确，原因是java异常处理用到了多态的概念，如果在异常处理过程中，首先捕获了父类，然后再捕获子类，那么捕获子类的代码将永远不会执行。

捕获到的异常不仅可以在当前方法处理，还可以将异常抛给调用它的上一级方法处理、

java.lang.Exception类是多有异常的直接或间接的父类，也就是所有异常的根类

Exception类的定义：public class Exception extends Throwable

Throwable类的定义: public class Throwable extends Object implements Serializable

Throwable实现了序列化的接口，因此可以被序列化。因为Exception是Throwable的子类，因此也可以被序列化。

java.lang.Throwable是在java语言中所有错误和异常的超类。

异常分为检查异常和运行异常，这两种异常有一个共同的父类Throwable.

检查异常，发生在编译阶段。一般这些异常通过处理后程序可以继续运行：IO异常、SQL异常

对可能出现异常的代码放在try中，对异常处理的代码放在catch中。

java编译器允许以下三种的异常处理方式
```text
try/catch
try/finally
try/catch/finally
```

在异常处理中，try只能有一个,finally块是可选的，但是最多只能有一个finally块；catch块可以有多个，但是必须遵从定义子类再定义父类的规则。

如果异常没有发生，catch块不会执行。一旦异常发生，异常按照catch块的先后顺序进行匹配，一旦匹配成功，则不会再和后面的catch块进行匹配。

finally在任何情况之下都会执行的。即使在try块内使用了return，那么在返回前，还是会执行finally块。












